root = "."
tmp_dir = "tmp"

[build]
# Build command.
cmd = "go build -o ./tmp/main ./cmd/server/main.go"
# Binary location
bin = "./tmp/main"
# Watch specific extensions
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore directories
exclude_dir = ["assets", "tmp", "vendor", "ent/migrate", "node_modules"]
# Delay to prevent partial writes triggering build
delay = 1000
# Stop running old binary when build errors occur
stop_on_error = true
# Send interrupt signal before killing process (graceful shutdown testing)
kill_delay = "500ms"

[log]
# Show timestamp
time = true

[color]
# Custom colors
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Clean tmp on exit
clean_on_exit = true