version: '3.8'

services:
  # --- RELATIONAL STORAGE ---
  db:
    image: postgres:16-alpine
    container_name: helix-shared-db
    environment:
      POSTGRES_USER: ${DB_USER:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev}
      POSTGRES_DB: ${DB_NAME:-{{ .EntityPluralLower }}}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dev -d {{ .EntityPluralLower }}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - helix-net

  # --- CACHE & IDEMPOTENCY ---
  redis:
    image: redis:7-alpine
    container_name: helix-shared-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
    networks:
      - helix-net

  # --- MESSAGE BROKER (REDPANDA) ---
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.6
    container_name: helix-shared-redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://helix-shared-redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
    networks:
      - helix-net

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: helix-shared-redpanda-console
    environment:
      - KAFKA_BROKERS=helix-shared-redpanda:29092
    ports:
      - "8081:8080"
    depends_on:
      - redpanda
    networks:
      - helix-net

networks:
  helix-net:
    name: helix-net
    driver: bridge

volumes:
  pg-data:
  redis-data:
  redpanda-data:
